### ISSUE TITLE
passwordHash

### ISSUE THREAD

**Issue by killyEma** [Jackgris/optima#19]
implementar las técnicas de hashing a las contraseñas de los usuarios

**Comment by jackgris** [comment]
La comparación es demasiado lenta, @killyEma  a vos no te pasa, que el login es demasiado lento ??

**Comment by killyEma** [comment]
si me tarda un minuto y algo mas, estoy viendo como se puede mejorar eso

**Comment by jackgris** [comment]
Creo que con los últimos cambios mejoró bastante, por lo menos por ahora :D b7a82ed75cbbe067925c74692f740844acbfea3d  @killyEma si vos crees que ya esta bien, podes cerrar este issue ;)

**Comment by killyEma** [comment]
si, creo que lo podemos dar por terminado!
